
export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_ADD_TO_CARTS = "SET_ADD_TO_CARTS";
export const SET_CLIENT = "SET_CLIENT";
export const SET_REAL_TIME_ORDERS = "SET_REAL_TIME_ORDERS";
export const SET_REAL_TIME_ORDER = "SET_REAL_TIME_ORDER";
export const SET_STORE_ID = "SET_STORE_ID";
export const SET_ROLE_MANAGEMENT = "SET_ROLE_MANAGEMENT";





 